export default [
  'function registerUser(address ethKey, uint256 starkKey, bytes calldata signature) external',
  'function deposit(uint256 starkKey, uint256 assetType, uint256 vaultId) external payable',
  'function deposit(uint256 starkKey, uint256 assetType, uint256 vaultId, uint256 quantizedAmount) public notFrozen()',
  'function depositCancel(uint256 starkKey, uint256 assetId, uint256 vaultId) external',
  'function depositReclaim(uint256 starkKey, uint256 assetId, uint256 vaultId) external isSenderStarkKey(starkKey)',
  'function withdraw(uint256 starkKey, uint256 assetType) external',
  'function withdrawTo(uint256 starkKey, uint256 assetType, address recipient) public',
  'function fullWithdrawalRequest(uint256 starkKey, uint256 vaultId) external notFrozen() isSenderStarkKey(starkKey)',
  'function freezeRequest(uint256 starkKey, uint256 vaultId) external notFrozen()',
  'function verifyEscape(uint256[] calldata escapeProof) external',
  'function escape(uint256 starkKey, uint256 vaultId, uint256 tokenId, uint256 quantizedAmount) external',
  'function depositNft(uint256 starkKey, uint256 assetType, uint256 vaultId, uint256 tokenId) external notFrozen()',
  'function depositNftReclaim(uint256 starkKey, uint256 assetType, uint256 vaultId, uint256 tokenId) external isSenderStarkKey(starkKey)',
  'function withdrawAndMint( uint256 starkKey, uint256 assetType, bytes calldata mintingBlob) external isSenderStarkKey(starkKey)',
  'function withdrawNft(uint256 starkKey, uint256 assetType, uint256 tokenId) external isSenderStarkKey(starkKey)',
  'function withdrawNftTo(uint256 starkKey, uint256 assetType, uint256 tokenId, address recipient) public isSenderStarkKey(starkKey)',
];
